version: '3.3'

networks:

  default:
    external:
      name: localstack-tutorial

volumes:

  localstack:

services:

  localstack:
    image: localstack/localstack:0.9.0
    ports:
      - 8080:8080 # webui
      - 4569:4569 # dynamodb
      - 4574:4574 # lamba
    environment:
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - DEFAULT_REGION=ap-southeast-2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker-reuse
      - PORT_WEB_UI=8080
      - SERVICES=lambda,dynamodb
      - LAMBDA_DOCKER_NETWORK=localstack-tutorial
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack:/tmp/localstack/data
